apiVersion: v1
kind: Service
metadata:
  name: auth-port-exposer
  labels:
    app: authentication
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
    - name: auth-port
      protocol: TCP
      port: 8083
      targetPort: 8083