apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: auth-cont
          imagePullPolicy: IfNotPresent
          image: t0pn0tch/auth-image:32
          ports:
            - name: auth-port
              containerPort: 8083
          env:
            - name: MYSQL_DATABASE
              value: websecurity
            - name: MYSQL_URL
              value: jdbc:mysql://database-port-exposer:3306/websecurity
          envFrom:
            - configMapRef:
                name: mysql-env-vars
            - configMapRef:
                name: gateway-env-vars
            - configMapRef:
                name: rabbitmq-env-vars
            