apiVersion: v1
kind: Service
metadata:
  name: doc-port-exposer
  labels:
    app: doc-service
spec:
  type: ClusterIP
  selector:
    app: doc-service
  ports:
    - name: doc-port
      protocol: TCP
      port: 8082
      targetPort: 8082