apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-env-vars
data:
    GATEWAY_SERVICE_HOST: "35.225.227.139"
    GATEWAY_SERVICE_PORT: "8081"
    
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-port-exposer
  labels:
    app: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - name: gateway-port
      protocol: TCP
      port: 8081
      targetPort: 8081
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-cont
          imagePullPolicy: Always
          image: t0pn0tch/gateway-image
          ports:
            - name: gateway-port
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: rabbitmq-env-vars
            - configMapRef:
                name: auth-env-vars
            - configMapRef:
                name: doc-env-vars
            