apiVersion: v1
kind: Service
metadata:
  name: gateway-port-exposer
  labels:
    app: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - name: gateway-port
      protocol: TCP
      port: 8081
      targetPort: 8081