apiVersion: v1
kind: Service
metadata:
  name: database-port-exposer
  labels:
    app: doc-db-server
spec:
  clusterIP: None
  selector:
    app: doc-db-server
  ports:
    - port: 3306
      targetPort: 3306