apiVersion: v1
kind: ConfigMap
metadata:
    name: rabbitmq-env-vars
data:
    BROKER_HOST: rabbitmq-port-exposer
    BROKER_PORT: "5672"
    
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-port-exposer
  labels:
    app: mssg-broker
spec:
  type: LoadBalancer
  selector:
    app: mssg-broker
  ports:
    - name: broker-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    app: mssg-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssg-broker
  template:
    metadata:
      labels:
        app: mssg-broker
    spec:
      containers:
        - name: mssg-broker-service
          imagePullPolicy: Always
          image: rabbitmq:3.9.2-management
          ports:
            - name: rabbitmq-broker
              containerPort: 5672
            - name: broker-display
              containerPort: 15672